/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemagestionnotas;

/**
 *
 * @author Sebastián
 */
public class IframeDocente extends javax.swing.JInternalFrame {

    /**
     * Creates new form IframeDocente
     */
    public IframeDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCoordinacion2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableCronograma2 = new javax.swing.JTable();
        lblNumActividad2 = new javax.swing.JLabel();
        txtNumActividad2 = new javax.swing.JTextField();
        lblActividad2 = new javax.swing.JLabel();
        txtActividad2 = new javax.swing.JTextField();
        lblDuracion2 = new javax.swing.JLabel();
        txtDuracion2 = new javax.swing.JTextField();
        lblFechaInicio2 = new javax.swing.JLabel();
        txtFechaInicio2 = new javax.swing.JTextField();
        lblFechaFin2 = new javax.swing.JLabel();
        txtFechaFin2 = new javax.swing.JTextField();
        btnConsultar2 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setTitle("Bienvenido Docente");

        panelCoordinacion2.setBackground(new java.awt.Color(0, 204, 255));

        jScrollPane5.setBackground(new java.awt.Color(0, 0, 0));

        tableCronograma2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tile 1", "Title 2", "Title 3", "Title 4", "ttttt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableCronograma2);

        jScrollPane5.setViewportView(jScrollPane6);

        lblNumActividad2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNumActividad2.setForeground(new java.awt.Color(255, 255, 255));
        lblNumActividad2.setText("Número de Actividad");

        lblActividad2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblActividad2.setForeground(new java.awt.Color(255, 255, 255));
        lblActividad2.setText("Actividad");

        lblDuracion2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDuracion2.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracion2.setText("Duración");

        lblFechaInicio2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblFechaInicio2.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaInicio2.setText("Fecha de Inicio");

        lblFechaFin2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblFechaFin2.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaFin2.setText("Fecha de Fin");

        btnConsultar2.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnConsultar2.setText("Consultar");
        btnConsultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar2ActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCoordinacion2Layout = new javax.swing.GroupLayout(panelCoordinacion2);
        panelCoordinacion2.setLayout(panelCoordinacion2Layout);
        panelCoordinacion2Layout.setHorizontalGroup(
            panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(btnConsultar2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnModificar)
                                .addGap(44, 44, 44)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblFechaFin2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFechaFin2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblFechaInicio2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFechaInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblDuracion2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDuracion2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblActividad2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtActividad2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblNumActividad2)
                                .addGap(29, 29, 29)
                                .addComponent(txtNumActividad2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelCoordinacion2Layout.setVerticalGroup(
            panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumActividad2)
                    .addComponent(txtNumActividad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActividad2)
                    .addComponent(txtActividad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracion2)
                    .addComponent(txtDuracion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicio2)
                    .addComponent(txtFechaInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaFin2)
                    .addComponent(txtFechaFin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnConsultar2)
                    .addComponent(btnSalir)
                    .addComponent(btnEliminar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCoordinacion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCoordinacion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar2ActionPerformed
        
    }//GEN-LAST:event_btnConsultar2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnConsultar2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblActividad;
    private javax.swing.JLabel lblActividad1;
    private javax.swing.JLabel lblActividad2;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblDuracion1;
    private javax.swing.JLabel lblDuracion2;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaFin1;
    private javax.swing.JLabel lblFechaFin2;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFechaInicio1;
    private javax.swing.JLabel lblFechaInicio2;
    private javax.swing.JLabel lblNumActividad;
    private javax.swing.JLabel lblNumActividad1;
    private javax.swing.JLabel lblNumActividad2;
    private javax.swing.JPanel panelCoordinacion;
    private javax.swing.JPanel panelCoordinacion1;
    private javax.swing.JPanel panelCoordinacion2;
    private javax.swing.JTable tableCronograma;
    private javax.swing.JTable tableCronograma1;
    private javax.swing.JTable tableCronograma2;
    private javax.swing.JTextField txtActividad;
    private javax.swing.JTextField txtActividad1;
    private javax.swing.JTextField txtActividad2;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtDuracion1;
    private javax.swing.JTextField txtDuracion2;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaFin1;
    private javax.swing.JTextField txtFechaFin2;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtFechaInicio1;
    private javax.swing.JTextField txtFechaInicio2;
    private javax.swing.JTextField txtNumActividad;
    private javax.swing.JTextField txtNumActividad1;
    private javax.swing.JTextField txtNumActividad2;
    // End of variables declaration//GEN-END:variables
}
