/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemagestionnotas;

/**
 *
 * @author Administrador
 */
public class IframeMatrícula extends javax.swing.JInternalFrame {

    /**
     * Creates new form IframeMatrícula
     */
    public IframeMatrícula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCoordinacion2 = new javax.swing.JPanel();
        scrollMatricula = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaMatricula = new javax.swing.JTable();
        lblNumMatricula = new javax.swing.JLabel();
        txtNumMatricula = new javax.swing.JTextField();
        lblCedSecre = new javax.swing.JLabel();
        txtCedSecre = new javax.swing.JTextField();
        lblCodMateria = new javax.swing.JLabel();
        txtCodMate = new javax.swing.JTextField();
        lblCedDocen = new javax.swing.JLabel();
        txtCedDocen = new javax.swing.JTextField();
        lblCedEstu = new javax.swing.JLabel();
        txtCedEstu = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtAño = new javax.swing.JTextField();
        lblAño = new javax.swing.JLabel();

        setTitle("Bienvenido Secreatario");
        setToolTipText("");

        panelCoordinacion2.setBackground(new java.awt.Color(0, 204, 255));

        scrollMatricula.setBackground(new java.awt.Color(0, 0, 0));

        tablaMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tile 1", "Title 2", "Title 3", "Title 4", "ttttt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaMatricula);

        scrollMatricula.setViewportView(jScrollPane6);

        lblNumMatricula.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNumMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lblNumMatricula.setText("Número de Matrícula");

        lblCedSecre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblCedSecre.setForeground(new java.awt.Color(255, 255, 255));
        lblCedSecre.setText("Cédula Secretario");

        lblCodMateria.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblCodMateria.setForeground(new java.awt.Color(255, 255, 255));
        lblCodMateria.setText("Código Materia");

        lblCedDocen.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblCedDocen.setForeground(new java.awt.Color(255, 255, 255));
        lblCedDocen.setText("Cédula Docente");

        lblCedEstu.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblCedEstu.setForeground(new java.awt.Color(255, 255, 255));
        lblCedEstu.setText("Cédula Estudiante");

        btnConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblAño.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblAño.setForeground(new java.awt.Color(255, 255, 255));
        lblAño.setText("Año en Curso");

        javax.swing.GroupLayout panelCoordinacion2Layout = new javax.swing.GroupLayout(panelCoordinacion2);
        panelCoordinacion2.setLayout(panelCoordinacion2Layout);
        panelCoordinacion2Layout.setHorizontalGroup(
            panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblCedEstu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCedEstu, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblCedDocen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCedDocen, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblCodMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodMate, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblCedSecre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCedSecre, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblNumMatricula)
                                .addGap(29, 29, 29)
                                .addComponent(txtNumMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(lblAño)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btnModificar)
                                .addGap(42, 42, 42)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelCoordinacion2Layout.setVerticalGroup(
            panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoordinacion2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumMatricula)
                    .addComponent(txtNumMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedSecre)
                    .addComponent(txtCedSecre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodMateria)
                    .addComponent(txtCodMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedDocen)
                    .addComponent(txtCedDocen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedEstu)
                    .addComponent(txtCedEstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAño)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(scrollMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panelCoordinacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnSalir))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCoordinacion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCoordinacion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCedDocen;
    private javax.swing.JLabel lblCedEstu;
    private javax.swing.JLabel lblCedSecre;
    private javax.swing.JLabel lblCodMateria;
    private javax.swing.JLabel lblNumMatricula;
    private javax.swing.JPanel panelCoordinacion2;
    private javax.swing.JScrollPane scrollMatricula;
    private javax.swing.JTable tablaMatricula;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCedDocen;
    private javax.swing.JTextField txtCedEstu;
    private javax.swing.JTextField txtCedSecre;
    private javax.swing.JTextField txtCodMate;
    private javax.swing.JTextField txtNumMatricula;
    // End of variables declaration//GEN-END:variables
}
